### ISSUE TITLE
Module not found: Can't resolve 'styled-components' in '/home/user/project/node_modules/react-vertical-tree/dist'

### ISSUE THREAD

**Issue by Rahulvs10** [seviltagiyeva/react-vertical-tree#1]
Installed the package and compiled the app. Got this compilation error.

**Comment by MrN-Nabhani** [comment]
Am having a similar issue here.

**Comment by MrN-Nabhani** [comment]
Apparently I just had to install the 'styled-components':
`npm install styled-components --save`
fixed it for me!
